import 'package:freezed_annotation/freezed_annotation.dart';

part 'chat_model.freezed.dart';

part 'chat_model.g.dart';

@unfreezed
class ChatModel with _$ChatModel {
  factory ChatModel({
    String? content,
    @JsonKey(name: 'content_type') String? contentType,
    @JsonKey(name: 'created_at') String? createdAt,
    int? id,
    @JsonKey(name: 'receiver_id') int? receiverId,
    @JsonKey(name: 'sender_id') int? senderId,
    String? status,
    String? messageTime,
    bool? isSender,
  }) = _ChatModel;

  factory ChatModel.fromJson(Map<String, dynamic> json) =>
      _$ChatModelFromJson(json);
}

final List<ChatModel> dummyChatList = [
  ChatModel(
    content: "Hey! Are you coming to the meeting?",
    contentType: "text",
    createdAt: "2025-07-23T09:00:00Z",
    id: 1,
    receiverId: 101,
    senderId: 100,
    status: "sent",
    messageTime: "9:00 AM",
    isSender: true,
  ),
  ChatModel(
    content: "Yes, I’ll be there in 5 minutes.",
    contentType: "text",
    createdAt: "2025-07-23T09:01:00Z",
    id: 2,
    receiverId: 100,
    senderId: 101,
    status: "delivered",
    messageTime: "9:01 AM",
    isSender: false,
  ),
  ChatModel(
    content: "Don’t forget to bring the report.",
    contentType: "text",
    createdAt: "2025-07-23T09:02:00Z",
    id: 3,
    receiverId: 101,
    senderId: 100,
    status: "seen",
    messageTime: "9:02 AM",
    isSender: true,
  ),
  ChatModel(
    content: "Of course, got it right here!",
    contentType: "text",
    createdAt: "2025-07-23T09:03:00Z",
    id: 4,
    receiverId: 100,
    senderId: 101,
    status: "sent",
    messageTime: "9:03 AM",
    isSender: false,
  ),
  ChatModel(
    content: "📷 Sent an image",
    contentType: "image",
    createdAt: "2025-07-23T09:05:00Z",
    id: 5,
    receiverId: 101,
    senderId: 100,
    status: "delivered",
    messageTime: "9:05 AM",
    isSender: true,
  ),
  ChatModel(
    content: "Nice! This will help a lot.",
    contentType: "text",
    createdAt: "2025-07-23T09:06:00Z",
    id: 6,
    receiverId: 100,
    senderId: 101,
    status: "seen",
    messageTime: "9:06 AM",
    isSender: false,
  ),
  ChatModel(
    content: "Let’s meet in the main conference room.",
    contentType: "text",
    createdAt: "2025-07-23T09:08:00Z",
    id: 7,
    receiverId: 101,
    senderId: 100,
    status: "sent",
    messageTime: "9:08 AM",
    isSender: true,
  ),
  ChatModel(
    content: "Got it. See you there!",
    contentType: "text",
    createdAt: "2025-07-23T09:09:00Z",
    id: 8,
    receiverId: 100,
    senderId: 101,
    status: "delivered",
    messageTime: "9:09 AM",
    isSender: false,
  ),
  ChatModel(
    content: "Let’s sync after the meeting.",
    contentType: "text",
    createdAt: "2025-07-23T10:00:00Z",
    id: 9,
    receiverId: 101,
    senderId: 100,
    status: "seen",
    messageTime: "10:00 AM",
    isSender: true,
  ),
  ChatModel(
    content: "Sure. I’ll bring the updated slide deck.",
    contentType: "text",
    createdAt: "2025-07-23T10:05:00Z",
    id: 10,
    receiverId: 100,
    senderId: 101,
    status: "sent",
    messageTime: "10:05 AM",
    isSender: false,
  ),
  ChatModel(
    content: "👍 Great! Thanks.",
    contentType: "text",
    createdAt: "2025-07-23T10:10:00Z",
    id: 11,
    receiverId: 101,
    senderId: 100,
    status: "delivered",
    messageTime: "10:10 AM",
    isSender: true,
  ),
  ChatModel(
    content: "See you soon!",
    contentType: "text",
    createdAt: "2025-07-23T10:12:00Z",
    id: 12,
    receiverId: 100,
    senderId: 101,
    status: "seen",
    messageTime: "10:12 AM",
    isSender: false,
  ),
];
